# @generated — do not edit directly.
# Regenerate with: python3 scripts/gen-pepper-commands.py
# Or via: make commands
"""Command name constants derived from Swift handler commandName properties.

Import these instead of bare strings to get typo-safety and IDE completion::

    # example
    from pepper_commands import CMD_TAP, CMD_SCROLL
    return await act_and_look(simulator, CMD_TAP, params)
"""


CMD_ACCESSIBILITY_ACTION = "accessibility_action"
CMD_ACCESSIBILITY_AUDIT = "accessibility_audit"
CMD_ACCESSIBILITY_EVENTS = "accessibility_events"
CMD_ANIMATIONS = "animations"
CMD_APPEARANCE = "appearance"
CMD_ASSERT = "assert"
CMD_BACK = "back"
CMD_BATCH = "batch"
CMD_CLIPBOARD = "clipboard"
CMD_CONCURRENCY = "concurrency"
CMD_CONSOLE = "console"
CMD_CONSTRAINTS = "constraints"
CMD_COOKIES = "cookies"
CMD_COREDATA = "coredata"
CMD_DEEPLINKS = "deeplinks"
CMD_DEFAULTS = "defaults"
CMD_DIALOG = "dialog"
CMD_DIFF = "diff"
CMD_DISMISS = "dismiss"
CMD_DISMISS_KEYBOARD = "dismiss_keyboard"
CMD_DYNAMIC_TYPE = "dynamic_type"
CMD_FIND = "find"
CMD_FLAGS = "flags"
CMD_FORMATTERS = "formatters"
CMD_FRAMEWORKS = "frameworks"
CMD_GESTURE = "gesture"
CMD_HANGS = "hangs"
CMD_HEAP = "heap"
CMD_HEAP_SNAPSHOT = "heap_snapshot"
CMD_HIGHLIGHT = "highlight"
CMD_HOOK = "hook"
CMD_IDENTIFY_ICONS = "identify_icons"
CMD_IDENTIFY_SELECTED = "identify_selected"
CMD_INPUT = "input"
CMD_INTROSPECT = "introspect"
CMD_KEYCHAIN = "keychain"
CMD_LAYERS = "layers"
CMD_LIFECYCLE = "lifecycle"
CMD_LOADING = "loading"
CMD_LOCALE = "locale"
CMD_MEMORY = "memory"
CMD_NAVIGATE = "navigate"
CMD_NETWORK = "network"
CMD_NOTIFICATIONS = "notifications"
CMD_ORIENTATION = "orientation"
CMD_PERF = "perf"
CMD_PUSH = "push"
CMD_READ = "read"
CMD_RENDERS = "renders"
CMD_RESPONDER_CHAIN = "responder_chain"
CMD_SANDBOX = "sandbox"
CMD_SCREEN = "screen"
CMD_SCREENSHOT = "screenshot"
CMD_SCROLL = "scroll"
CMD_SCROLL_TO = "scroll_to"
CMD_SNAPSHOT = "snapshot"
CMD_STATUS = "status"
CMD_STORAGE = "storage"
CMD_SWIFTUI_BODY = "swiftui_body"
CMD_SWIPE = "swipe"
CMD_SWIZZLE_CHECK = "swizzle_check"
CMD_TAP = "tap"
CMD_TARGET_ACTIONS = "target_actions"
CMD_TEST = "test"
CMD_TIMELINE = "timeline"
CMD_TIMERS = "timers"
CMD_TOGGLE = "toggle"
CMD_TREE = "tree"
CMD_UNDO = "undo"
CMD_VARS = "vars"
CMD_VERIFY = "verify"
CMD_WAIT_FOR = "wait_for"
CMD_WAIT_IDLE = "wait_idle"
CMD_WEBVIEW = "webview"

# Alias used internally for the look/introspect map command
CMD_LOOK = "look"
