#!/usr/bin/env python3
"""Generate docs/COMMANDS.md from MCP tool definitions in tools/pepper-mcp.

Source of truth: tools/pepper-mcp (@mcp.tool() decorated functions)
Extracts: function name, docstring, Field() parameters with descriptions.

Usage:
  python3 scripts/gen-commands.py          # write docs/COMMANDS.md
  python3 scripts/gen-commands.py --check  # exit 1 if stale
"""

import ast
import os
import re
import sys
import textwrap

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MCP_FILE = os.path.join(ROOT, "tools", "pepper-mcp")
OUTPUT_FILE = os.path.join(ROOT, "docs", "COMMANDS.md")


def parse_mcp_tools():
    """Parse @mcp.tool() decorated functions from pepper-mcp."""
    with open(MCP_FILE) as f:
        source = f.read()

    # Parse AST
    tree = ast.parse(source)

    tools = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.AsyncFunctionDef):
            continue

        # Check if decorated with @mcp.tool()
        is_tool = False
        for dec in node.decorator_list:
            if isinstance(dec, ast.Call) and isinstance(dec.func, ast.Attribute):
                if dec.func.attr == "tool":
                    is_tool = True
            elif isinstance(dec, ast.Attribute) and dec.attr == "tool":
                is_tool = True
        if not is_tool:
            continue

        # Extract function name
        name = node.name

        # Extract docstring
        docstring = ast.get_docstring(node) or ""

        # Extract parameters from source (AST doesn't preserve Field() defaults well)
        params = parse_params_from_source(source, node)

        tools.append({
            "name": name,
            "docstring": docstring.strip(),
            "params": params,
            "line": node.lineno,
        })

    return tools


def parse_params_from_source(source, node):
    """Extract parameter names, types, and Field descriptions from source."""
    lines = source.split("\n")
    params = []

    # Get the function signature lines
    start = node.lineno - 1  # 0-indexed
    # Find the closing ) -> or ) :
    sig_lines = []
    paren_depth = 0
    for i in range(start, min(start + 30, len(lines))):
        line = lines[i]
        sig_lines.append(line)
        paren_depth += line.count("(") - line.count(")")
        if paren_depth <= 0 and (")" in line):
            break

    sig = "\n".join(sig_lines)

    # Parse each param: name: Type = Field(default=..., description="...")
    for m in re.finditer(
        r'(\w+):\s*([^=]+?)\s*=\s*Field\([^)]*description="([^"]*)"[^)]*\)',
        sig,
    ):
        param_name = m.group(1)
        param_type = m.group(2).strip()
        description = m.group(3)

        # Skip simulator param — it's on every tool, not interesting
        if param_name == "simulator":
            continue

        # Clean up type
        param_type = param_type.replace("Optional[", "").replace("]", "")

        # Check if required (no default= in Field)
        field_call = m.group(0)
        required = "default=" not in field_call and "default =" not in field_call

        params.append({
            "name": param_name,
            "type": param_type,
            "description": description,
            "required": required,
        })

    return params


# Tool categories — derived from the MCP server's tool grouping
# Keep this minimal; if a tool isn't listed, it goes in "other"
CATEGORIES = {
    "observation": ["look", "tree", "read_element", "find", "highlight",
                     "screen", "status"],
    "interaction": ["tap", "scroll", "scroll_to", "swipe", "gesture",
                     "input_text", "toggle", "navigate", "back", "dismiss",
                     "dismiss_keyboard", "dialog", "push", "orientation"],
    "inspection":  ["vars_inspect", "heap", "layers", "console", "network",
                     "animations", "hook", "timeline", "crash_log"],
    "data":        ["defaults", "clipboard", "keychain", "cookies", "locale",
                     "flags"],
    "flow":        ["wait_for", "wait_idle", "record", "raw"],
    "build":       ["build", "build_device", "deploy", "iterate", "simulator"],
}

def get_category(name):
    for cat, tools in CATEGORIES.items():
        if name in tools:
            return cat
    return "other"

CATEGORY_ORDER = ["observation", "interaction", "inspection", "data",
                   "flow", "build", "other"]
CATEGORY_TITLES = {
    "observation": "Observation",
    "interaction": "Interaction",
    "inspection": "Inspection & Debugging",
    "data": "Data & Configuration",
    "flow": "Flow Control",
    "build": "Build & Deploy",
    "other": "Other",
}


def generate_markdown(tools):
    """Generate COMMANDS.md content."""
    lines = [
        "<!-- AUTO-GENERATED by scripts/gen-commands.py — do not edit by hand -->",
        "# Command Reference",
        "",
        "All Pepper commands exposed via MCP tools. Auto-generated from `tools/pepper-mcp`.",
        "",
        "## Summary",
        "",
        f"**{len(tools)} tools** available.",
        "",
        "| Tool | Description |",
        "|------|-------------|",
    ]

    for tool in tools:
        # First line of docstring as summary
        summary = tool["docstring"].split("\n")[0] if tool["docstring"] else ""
        lines.append(f"| `{tool['name']}` | {summary} |")

    lines.append("")

    # Group by category
    grouped = {}
    for tool in tools:
        cat = get_category(tool["name"])
        grouped.setdefault(cat, []).append(tool)

    for cat in CATEGORY_ORDER:
        if cat not in grouped:
            continue
        title = CATEGORY_TITLES.get(cat, cat.title())
        lines.append(f"## {title}")
        lines.append("")

        for tool in grouped[cat]:
            lines.append(f"### `{tool['name']}`")
            lines.append("")
            if tool["docstring"]:
                lines.append(tool["docstring"])
                lines.append("")

            if tool["params"]:
                lines.append("| Param | Type | Required | Description |")
                lines.append("|-------|------|----------|-------------|")
                for p in tool["params"]:
                    req = "yes" if p["required"] else "—"
                    lines.append(f"| `{p['name']}` | {p['type']} | {req} | {p['description']} |")
                lines.append("")

    # Protocol section (keep this static — it's format docs, not tool docs)
    lines.extend([
        "## WebSocket Protocol",
        "",
        "Commands can also be sent directly via WebSocket to `ws://localhost:<port>`.",
        "",
        "```json",
        '{"id": "abc123", "cmd": "command_name", "params": {...}}',
        "```",
        "",
        "Response: `{\"id\": \"abc123\", \"status\": \"ok\", \"data\": {...}}`",
        "",
    ])

    return "\n".join(lines) + "\n"


def main():
    check_mode = "--check" in sys.argv

    tools = parse_mcp_tools()
    md = generate_markdown(tools)

    if check_mode:
        if os.path.exists(OUTPUT_FILE):
            with open(OUTPUT_FILE) as f:
                existing = f.read()
            if existing == md:
                print("COMMANDS.md is up to date.")
                sys.exit(0)
            else:
                print("COMMANDS.md is stale. Run: make commands")
                sys.exit(1)
        else:
            print("COMMANDS.md does not exist. Run: make commands")
            sys.exit(1)

    with open(OUTPUT_FILE, "w") as f:
        f.write(md)

    print(f"Generated {OUTPUT_FILE}")
    print(f"  {len(tools)} tools")


if __name__ == "__main__":
    main()
