import UIKit

/// Called from the C constructor in bootstrap.c when the dylib loads.
/// Registers for didFinishLaunchingNotification to start the control
/// plane at the correct app lifecycle point.
///
/// In static-library mode (SPM link), this file is harmless — AppDelegate
/// calls PepperPlane.shared.start() directly and the notification observer
/// here just no-ops (start() is idempotent).
@_cdecl("PepperBootstrap")
public func pepperBootstrap() {
    // Register the app adapter bootstrap based on the PEPPER_ADAPTER env var.
    // Known adapters register here; "generic" or unset means no app-specific config.
    // The dashboard sets this env var at launch via SIMCTL_CHILD_PEPPER_ADAPTER.
    let adapterType = ProcessInfo.processInfo.environment["PEPPER_ADAPTER"] ?? "generic"
    PepperAppConfig.shared.requestedAdapterType = adapterType

    // Register the app adapter. Each adapter sets preMainHook (early setup
    // like flag overrides) and appBootstrap (full configuration at start).
    // _AdapterShim is auto-generated by the build script from ADAPTER_PATH.
    #if PEPPER_HAS_ADAPTER
        _PepperAdapterShim.register(adapterType: adapterType)
    #endif

    // Validate adapter configuration at startup.
    if adapterType != "generic" {
        #if !PEPPER_HAS_ADAPTER
            NSLog(
                "[pepper] ⚠️ PEPPER_ADAPTER='%@' but no adapter was compiled in — build with ADAPTER_PATH set",
                adapterType)
        #else
            if !PepperAppConfig.shared.adapterRegistered {
                NSLog(
                    "[pepper] ⚠️ PEPPER_ADAPTER='%@' did not match any compiled adapter — check APP_ADAPTER_TYPE in .env",
                    adapterType)
            }
        #endif
    }

    // Run pre-main hook immediately — this executes at dylib load time,
    // BEFORE main() and before the app's own initialization code runs.
    PepperAppConfig.shared.preMainHook?()

    // Install authorization auto-grant swizzles early — BEFORE didFinishLaunchingWithOptions.
    // Apps commonly call UNUserNotificationCenter.requestAuthorization or
    // PHPhotoLibrary.requestAuthorization during launch. If we wait until
    // didFinishLaunchingNotification (which fires AFTER the delegate method returns),
    // the system dialog has already appeared. Installing here ensures the swizzle
    // is in place before any app code runs.
    PepperDialogInterceptor.installAuthorizationSwizzles()

    // VoiceOver interposition is handled by accessibility_hook.c (DYLD_INTERPOSE)
    // at dylib load. The status-change notification is posted later by
    // PepperPlane.start() via PepperAccessibility.postVoiceOverNotification().

    NotificationCenter.default.addObserver(
        forName: UIApplication.didFinishLaunchingNotification,
        object: nil,
        queue: .main
    ) { _ in
        // Reinforce the notification authorization swizzle on every
        // UNUserNotificationCenter subclass now that the runtime is fully
        // initialized. The base-class swizzle (installed at constructor time)
        // covers the common case, but private subclasses that override
        // requestAuthorization need individual swizzling.
        // Class enumeration uses a C helper to avoid swift_dynamicCast crash
        // on iOS 26.3 (BUG-766).
        if ProcessInfo.processInfo.environment["PEPPER_SKIP_PERMISSIONS"] != "1" {
            PepperDialogInterceptor.reinforceNotificationSwizzle()
        }

        // Resolve port: PEPPER_PORT env var > PepperPort Info.plist key > auto-detect from UDID > default 8765
        let port: UInt16
        let udid: String?

        if let envPort = ProcessInfo.processInfo.environment["PEPPER_PORT"],
            let parsed = UInt16(envPort)
        {
            port = parsed
            udid =
                ProcessInfo.processInfo.environment["PEPPER_SIM_UDID"]
                ?? PepperSimDetect.detectUDID()
        } else if let plistPort = Bundle.main.infoDictionary?["PepperPort"],
            let parsed = (plistPort as? Int).map(UInt16.init)
                ?? (plistPort as? String).flatMap(UInt16.init)
        {
            // Info.plist key — useful when env vars aren't available (e.g. app-clip, on-device builds).
            port = parsed
            udid =
                ProcessInfo.processInfo.environment["PEPPER_SIM_UDID"]
                ?? PepperSimDetect.detectUDID()
        } else if let detected = PepperSimDetect.detectUDID() {
            // Auto-detect: compute the same deterministic port as the Makefile
            // (8770 + md5(udid)[:4] % 100) so pepper-ctl discovers us on the same port.
            port = PepperSimDetect.portFromUDID(detected)
            udid = detected
        } else {
            // On-device: no simulator UDID available. Use default port.
            // Log the device's WiFi IP so the user knows where to connect.
            port = 8765
            udid = nil
            if let ip = PepperNetworkInfo.wifiIPAddress() {
                NSLog("[pepper] Device mode — connect via ws://\(ip):\(port)")
            }
        }

        PepperPlane.shared.start(port: port, simulatorUDID: udid)
    }
}

// MARK: - Simulator auto-detection

/// Extracts the simulator UDID from the runtime environment and computes
/// the deterministic port — matching the Makefile algorithm exactly.
enum PepperSimDetect {

    /// Extract the simulator device UDID from NSHomeDirectory().
    /// Simulator home paths contain: CoreSimulator/Devices/<UDID>/data/...
    static func detectUDID() -> String? {
        let home = NSHomeDirectory()
        guard let range = home.range(of: "CoreSimulator/Devices/") else { return nil }
        let afterDevices = home[range.upperBound...]
        guard let slashIdx = afterDevices.firstIndex(of: "/") else { return nil }
        let udid = String(afterDevices[..<slashIdx])
        // Sanity check: UUIDs are 36 chars (8-4-4-4-12)
        guard udid.count == 36 else { return nil }
        return udid
    }

    /// Compute the deterministic port from a simulator UDID.
    /// Algorithm: 8770 + int(md5(udid).hexdigest()[:4], 16) % 100
    /// This MUST match the Makefile's Python one-liner exactly.
    static func portFromUDID(_ udid: String) -> UInt16 {
        let data = Array(udid.utf8)
        var hash = [UInt8](repeating: 0, count: 16)
        data.withUnsafeBufferPointer { buf in
            // swiftlint:disable:next force_unwrapping
            pepper_md5(buf.baseAddress!, UInt32(buf.count), &hash)
        }
        // First 4 hex chars = first 2 bytes, big-endian
        let value = UInt16(hash[0]) << 8 | UInt16(hash[1])
        return 8770 + value % 100
    }
}

// Declare the C helper from pepper_md5.c
@_silgen_name("pepper_md5")
private func pepper_md5(_ data: UnsafeRawPointer, _ len: UInt32, _ out: UnsafeMutablePointer<UInt8>)
