#!/bin/bash
set -euo pipefail

# Build Pepper as an XCFramework containing both device and simulator slices.
#
# Output: build/Pepper.xcframework/
#
# Usage:
#   ./tools/build-xcframework.sh              # build xcframework
#   ./tools/build-xcframework.sh --clean      # clean + build
#   ./tools/build-xcframework.sh --sim-only   # simulator slice only (faster)

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
CONTROL_DIR="$PROJECT_DIR/dylib"

WORKTREE_ROOT=$(git -C "$PROJECT_DIR" rev-parse --show-toplevel 2>/dev/null || echo "$PROJECT_DIR")
BUILD_DIR="$WORKTREE_ROOT/build/xcframework"
XCFRAMEWORK_DIR="$WORKTREE_ROOT/build/Pepper.xcframework"

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
BOLD='\033[1m'
NC='\033[0m'

info()    { echo -e "${BLUE}xcframework:${NC} $*"; }
success() { echo -e "${GREEN}xcframework:${NC} $*"; }
error()   { echo -e "${RED}xcframework:${NC} $*" >&2; }

# --- Options ---
CLEAN=""
SIM_ONLY=""
for arg in "$@"; do
    case "$arg" in
        --clean)    CLEAN=1 ;;
        --sim-only) SIM_ONLY=1 ;;
    esac
done

if [ -n "$CLEAN" ]; then
    info "Cleaning xcframework build directory..."
    rm -rf "$BUILD_DIR" "$XCFRAMEWORK_DIR"
fi

IOS_TARGET_VERSION="${IOS_TARGET_VERSION:-18.0}"

# --- Load .env for adapter config ---
ENV_FILE="$PROJECT_DIR/.env"
ADAPTER_PATH=""
ADAPTER_TYPE=""
if [ -f "$ENV_FILE" ]; then
    ADAPTER_PATH=$(set -a && source "$ENV_FILE" 2>/dev/null && echo "$ADAPTER_PATH")
    ADAPTER_TYPE=$(set -a && source "$ENV_FILE" 2>/dev/null && echo "${APP_ADAPTER_TYPE:-}")
fi

# --- Gather sources ---
SOURCE_DIRS=("$CONTROL_DIR")
HAS_ADAPTER=""
if [ -n "$ADAPTER_PATH" ] && [ -d "$ADAPTER_PATH" ]; then
    SOURCE_DIRS+=("$ADAPTER_PATH")
    info "Adapter: $ADAPTER_PATH"

    if [ -n "$ADAPTER_TYPE" ]; then
        BOOTSTRAP_MATCHES=$(grep -rl 'static func registerAdapter' "$ADAPTER_PATH"/*.swift 2>/dev/null)
        BOOTSTRAP_COUNT=$(echo "$BOOTSTRAP_MATCHES" | grep -c . 2>/dev/null || true)
        if [ "$BOOTSTRAP_COUNT" -gt 1 ]; then
            error "Multiple files contain registerAdapter — expected exactly one:"
            echo "$BOOTSTRAP_MATCHES" >&2
            exit 1
        fi
        BOOTSTRAP_CLASS=$(echo "$BOOTSTRAP_MATCHES" | head -1 | xargs -I{} basename {} .swift 2>/dev/null)
        if [ -n "$BOOTSTRAP_CLASS" ]; then
            HAS_ADAPTER=1
            mkdir -p "$BUILD_DIR"
            cat > "$BUILD_DIR/_AdapterShim.swift" <<SHIM
// @generated by build-xcframework.sh
enum _PepperAdapterShim {
    static func register(adapterType: String) {
        switch adapterType {
        case "$ADAPTER_TYPE": $BOOTSTRAP_CLASS.registerAdapter()
        default: break
        }
    }
}
SHIM
        fi
    fi
fi

SWIFT_FILES=()
C_FILES=()
OBJC_FILES=()
for src_dir in "${SOURCE_DIRS[@]}"; do
    while IFS= read -r -d '' file; do
        SWIFT_FILES+=("$file")
    done < <(find "$src_dir" -name '*.swift' -print0)
    while IFS= read -r -d '' file; do
        C_FILES+=("$file")
    done < <(find "$src_dir" -name '*.c' -print0)
    while IFS= read -r -d '' file; do
        OBJC_FILES+=("$file")
    done < <(find "$src_dir" -name '*.m' -print0)
done

if [ -f "$BUILD_DIR/_AdapterShim.swift" ]; then
    SWIFT_FILES+=("$BUILD_DIR/_AdapterShim.swift")
fi

SWIFT_COUNT=${#SWIFT_FILES[@]}
C_COUNT=$(( ${#C_FILES[@]} + ${#OBJC_FILES[@]} ))

# --- Find bridging header ---
BRIDGING_HEADER=""
for m_file in "${OBJC_FILES[@]}"; do
    h_file="${m_file%.m}.h"
    if [ -f "$h_file" ]; then
        BRIDGING_HEADER="$BUILD_DIR/Pepper-Bridging-Header.h"
        break
    fi
done
if [ -n "$BRIDGING_HEADER" ]; then
    mkdir -p "$BUILD_DIR"
    > "$BRIDGING_HEADER"
    for m_file in "${OBJC_FILES[@]}"; do
        h_file="${m_file%.m}.h"
        if [ -f "$h_file" ]; then
            echo "#import \"$h_file\"" >> "$BRIDGING_HEADER"
        fi
    done
fi

# =============================================================
# build_slice SDK TARGET ARCH SLICE_DIR
#   Compiles C/ObjC + Swift and produces a .framework in SLICE_DIR.
# =============================================================
build_slice() {
    local sdk="$1"
    local target="$2"
    local arch="$3"
    local slice_dir="$4"
    local obj_dir="$BUILD_DIR/obj-${sdk}"

    local sdk_path
    sdk_path=$(xcrun --sdk "$sdk" --show-sdk-path)

    info "Building $sdk slice ($arch)..."
    info "  SDK: $sdk_path"
    info "  Target: $target"

    mkdir -p "$obj_dir" "$slice_dir/Modules/Pepper.swiftmodule"

    # --- Compile C/ObjC ---
    local c_objects=()
    local pids=()

    for c_file in "${C_FILES[@]}"; do
        local base
        base=$(basename "$c_file" .c)
        local obj="$obj_dir/${base}.o"
        xcrun -sdk "$sdk" clang \
            -target "$target" \
            -isysroot "$sdk_path" \
            -c "$c_file" \
            -o "$obj" &
        pids+=($!)
        c_objects+=("$obj")
    done

    for m_file in "${OBJC_FILES[@]}"; do
        local base
        base=$(basename "$m_file" .m)
        local obj="$obj_dir/${base}_objc.o"
        xcrun -sdk "$sdk" clang \
            -target "$target" \
            -isysroot "$sdk_path" \
            -fobjc-arc \
            -c "$m_file" \
            -o "$obj" &
        pids+=($!)
        c_objects+=("$obj")
    done

    for pid in "${pids[@]}"; do
        wait "$pid" || { error "C/ObjC compilation failed ($sdk)"; exit 1; }
    done

    # --- Compile Swift + link ---
    xcrun -sdk "$sdk" swiftc \
        -target "$target" \
        -sdk "$sdk_path" \
        -emit-library \
        -emit-module \
        -emit-module-path "$slice_dir/Modules/Pepper.swiftmodule/${arch}.swiftmodule" \
        -module-name Pepper \
        -o "$slice_dir/Pepper" \
        -Osize \
        -whole-module-optimization \
        -DPEPPER_CONTROL -DPEPPER \
        ${HAS_ADAPTER:+-DPEPPER_HAS_ADAPTER} \
        -framework UIKit \
        -framework Foundation \
        -framework Network \
        -framework SwiftUI \
        -framework QuartzCore \
        -framework AVFoundation \
        -framework CoreMedia \
        -framework EventKit \
        -framework AppTrackingTransparency \
        -framework Contacts \
        -framework CoreLocation \
        -Xlinker -install_name -Xlinker @rpath/Pepper.framework/Pepper \
        ${BRIDGING_HEADER:+-import-objc-header "$BRIDGING_HEADER"} \
        "${SWIFT_FILES[@]}" \
        "${c_objects[@]}"

    # --- Info.plist ---
    cat > "$slice_dir/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleIdentifier</key>
    <string>com.pepper.control</string>
    <key>CFBundleName</key>
    <string>Pepper</string>
    <key>CFBundleExecutable</key>
    <string>Pepper</string>
    <key>CFBundlePackageType</key>
    <string>FMWK</string>
    <key>CFBundleVersion</key>
    <string>1</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0</string>
    <key>MinimumOSVersion</key>
    <string>${IOS_TARGET_VERSION}</string>
</dict>
</plist>
PLIST

    local size
    size=$(stat -f%z "$slice_dir/Pepper" 2>/dev/null || stat --printf='%s' "$slice_dir/Pepper" 2>/dev/null)
    success "  $sdk slice: $((size / 1024))KB"
}

# =============================================================
# Build slices
# =============================================================

info "Compiling $SWIFT_COUNT Swift + $C_COUNT C/ObjC files..."

# Simulator slice — always arm64 on Apple Silicon, x86_64 on Intel
SIM_ARCH=$(uname -m)
SIM_TARGET="${SIM_ARCH}-apple-ios${IOS_TARGET_VERSION}-simulator"
SIM_FRAMEWORK="$BUILD_DIR/sim/Pepper.framework"
build_slice iphonesimulator "$SIM_TARGET" "$SIM_ARCH" "$SIM_FRAMEWORK"

FRAMEWORK_ARGS=(-framework "$SIM_FRAMEWORK")

if [ -z "$SIM_ONLY" ]; then
    # Device slice — always arm64
    DEVICE_TARGET="arm64-apple-ios${IOS_TARGET_VERSION}"
    DEVICE_FRAMEWORK="$BUILD_DIR/device/Pepper.framework"
    build_slice iphoneos "$DEVICE_TARGET" arm64 "$DEVICE_FRAMEWORK"
    FRAMEWORK_ARGS+=(-framework "$DEVICE_FRAMEWORK")
fi

# =============================================================
# Package into XCFramework
# =============================================================

info "Packaging XCFramework..."
rm -rf "$XCFRAMEWORK_DIR"

xcodebuild -create-xcframework \
    "${FRAMEWORK_ARGS[@]}" \
    -output "$XCFRAMEWORK_DIR"

success "Built Pepper.xcframework"
success "  $XCFRAMEWORK_DIR"
