#!/bin/bash
set -euo pipefail

# Build Pepper as a dynamic framework for iOS Simulator injection.
#
# Output: build/Pepper.framework/Pepper (Mach-O dylib)
#
# Usage:
#   ./tools/build-dylib.sh              # build for current sim arch
#   ./tools/build-dylib.sh --clean      # clean + build

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
CONTROL_DIR="$PROJECT_DIR/control"
BUILD_DIR="$PROJECT_DIR/build/dylib"
FRAMEWORK_DIR="$PROJECT_DIR/build/Pepper.framework"

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
BOLD='\033[1m'
NC='\033[0m'

info()    { echo -e "${BLUE}dylib:${NC} $*"; }
success() { echo -e "${GREEN}dylib:${NC} $*"; }
error()   { echo -e "${RED}dylib:${NC} $*" >&2; }

# --- Options ---
if [ "${1:-}" = "--clean" ]; then
    info "Cleaning build directory..."
    rm -rf "$BUILD_DIR" "$FRAMEWORK_DIR"
fi

# --- Detect architecture ---
# Apple Silicon Macs run arm64 simulators; Intel runs x86_64
ARCH=$(uname -m)
IOS_TARGET_VERSION="${IOS_TARGET_VERSION:-17.0}"
if [ "$ARCH" = "arm64" ]; then
    TARGET="arm64-apple-ios${IOS_TARGET_VERSION}-simulator"
else
    TARGET="x86_64-apple-ios${IOS_TARGET_VERSION}-simulator"
fi

# --- Find SDK ---
SDK_PATH=$(xcrun --sdk iphonesimulator --show-sdk-path)
info "SDK: $SDK_PATH"
info "Target: $TARGET"

# --- Load .env for adapter config ---
# Source the file in a subshell so it handles quoting, spaces, and comments natively
ENV_FILE="$PROJECT_DIR/.env"
ADAPTER_PATH=""
ADAPTER_TYPE=""
if [ -f "$ENV_FILE" ]; then
    ADAPTER_PATH=$(set -a && source "$ENV_FILE" 2>/dev/null && echo "$ADAPTER_PATH")
    ADAPTER_TYPE=$(set -a && source "$ENV_FILE" 2>/dev/null && echo "$APP_ADAPTER_TYPE")
fi

# --- Gather sources ---
SOURCE_DIRS=("$CONTROL_DIR")
HAS_ADAPTER=""
if [ -n "$ADAPTER_PATH" ] && [ -d "$ADAPTER_PATH" ]; then
    SOURCE_DIRS+=("$ADAPTER_PATH")
    info "Adapter: $ADAPTER_PATH"

    # Generate registration shim — wires the adapter's bootstrap into the loader
    if [ -n "$ADAPTER_TYPE" ]; then
        BOOTSTRAP_MATCHES=$(grep -rl 'static func registerAdapter' "$ADAPTER_PATH"/*.swift 2>/dev/null)
        BOOTSTRAP_COUNT=$(echo "$BOOTSTRAP_MATCHES" | grep -c . 2>/dev/null || true)
        if [ "$BOOTSTRAP_COUNT" -gt 1 ]; then
            error "Multiple files contain registerAdapter — expected exactly one:"
            echo "$BOOTSTRAP_MATCHES" >&2
            exit 1
        fi
        BOOTSTRAP_CLASS=$(echo "$BOOTSTRAP_MATCHES" | head -1 | xargs -I{} basename {} .swift 2>/dev/null)
        if [ -n "$BOOTSTRAP_CLASS" ]; then
            HAS_ADAPTER=1
            mkdir -p "$BUILD_DIR"
            cat > "$BUILD_DIR/_AdapterShim.swift" <<SHIM
// Auto-generated by build-dylib.sh — do not edit
enum _PepperAdapterShim {
    static func register(adapterType: String) {
        switch adapterType {
        case "$ADAPTER_TYPE": $BOOTSTRAP_CLASS.registerAdapter()
        default: break
        }
    }
}
SHIM
        fi
    fi
fi

SWIFT_FILES=()
C_FILES=()
OBJC_FILES=()
for src_dir in "${SOURCE_DIRS[@]}"; do
    while IFS= read -r -d '' file; do
        SWIFT_FILES+=("$file")
    done < <(find "$src_dir" -name '*.swift' -print0)
    while IFS= read -r -d '' file; do
        C_FILES+=("$file")
    done < <(find "$src_dir" -name '*.c' -print0)
    while IFS= read -r -d '' file; do
        OBJC_FILES+=("$file")
    done < <(find "$src_dir" -name '*.m' -print0)
done

# Include build-generated adapter shim if present
if [ -f "$BUILD_DIR/_AdapterShim.swift" ]; then
    SWIFT_FILES+=("$BUILD_DIR/_AdapterShim.swift")
fi

SWIFT_COUNT=${#SWIFT_FILES[@]}
C_COUNT=$(( ${#C_FILES[@]} + ${#OBJC_FILES[@]} ))
info "Compiling $SWIFT_COUNT Swift + $C_COUNT C/ObjC files..."

# --- Create output dirs ---
mkdir -p "$BUILD_DIR" "$FRAMEWORK_DIR/Modules/Pepper.swiftmodule"

# --- Step 1: Compile C/ObjC sources to object files (parallel) ---
C_OBJECTS=()
COMPILE_PIDS=()

for c_file in "${C_FILES[@]}"; do
    basename=$(basename "$c_file" .c)
    obj="$BUILD_DIR/${basename}.o"
    xcrun -sdk iphonesimulator clang \
        -target "$TARGET" \
        -isysroot "$SDK_PATH" \
        -c "$c_file" \
        -o "$obj" &
    COMPILE_PIDS+=($!)
    C_OBJECTS+=("$obj")
done

for m_file in "${OBJC_FILES[@]}"; do
    basename=$(basename "$m_file" .m)
    obj="$BUILD_DIR/${basename}_objc.o"
    xcrun -sdk iphonesimulator clang \
        -target "$TARGET" \
        -isysroot "$SDK_PATH" \
        -fobjc-arc \
        -c "$m_file" \
        -o "$obj" &
    COMPILE_PIDS+=($!)
    C_OBJECTS+=("$obj")
done

# Wait for all parallel C/ObjC compilations
for pid in "${COMPILE_PIDS[@]}"; do
    wait "$pid" || { error "C/ObjC compilation failed"; exit 1; }
done

# --- Find bridging header (if any .h files exist alongside .m files) ---
BRIDGING_HEADER=""
for m_file in "${OBJC_FILES[@]}"; do
    h_file="${m_file%.m}.h"
    if [ -f "$h_file" ]; then
        # Use a combined bridging header that imports all ObjC headers
        BRIDGING_HEADER="$BUILD_DIR/Pepper-Bridging-Header.h"
        break
    fi
done
if [ -n "$BRIDGING_HEADER" ]; then
    > "$BRIDGING_HEADER"
    for m_file in "${OBJC_FILES[@]}"; do
        h_file="${m_file%.m}.h"
        if [ -f "$h_file" ]; then
            echo "#import \"$h_file\"" >> "$BRIDGING_HEADER"
        fi
    done
fi

# --- Step 2: Compile Swift + link with C objects ---
xcrun -sdk iphonesimulator swiftc \
    -target "$TARGET" \
    -sdk "$SDK_PATH" \
    -emit-library \
    -emit-module \
    -emit-module-path "$FRAMEWORK_DIR/Modules/Pepper.swiftmodule/${ARCH}.swiftmodule" \
    -module-name Pepper \
    -o "$FRAMEWORK_DIR/Pepper" \
    -Osize \
    -whole-module-optimization \
    -DPEPPER_CONTROL -DPEPPER \
    ${HAS_ADAPTER:+-DPEPPER_HAS_ADAPTER} \
    -framework UIKit \
    -framework Foundation \
    -framework Network \
    -framework SwiftUI \
    -framework QuartzCore \
    -framework AVFoundation \
    -framework CoreMedia \
    -Xlinker -install_name -Xlinker @rpath/Pepper.framework/Pepper \
    ${BRIDGING_HEADER:+-import-objc-header "$BRIDGING_HEADER"} \
    "${SWIFT_FILES[@]}" \
    "${C_OBJECTS[@]}"

# --- Create Info.plist ---
cat > "$FRAMEWORK_DIR/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleIdentifier</key>
    <string>com.pepper.control</string>
    <key>CFBundleName</key>
    <string>Pepper</string>
    <key>CFBundleExecutable</key>
    <string>Pepper</string>
    <key>CFBundlePackageType</key>
    <string>FMWK</string>
    <key>CFBundleVersion</key>
    <string>1</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0</string>
    <key>MinimumOSVersion</key>
    <string>${IOS_TARGET_VERSION}</string>
</dict>
</plist>
PLIST

# --- Report ---
DYLIB_SIZE=$(stat -f%z "$FRAMEWORK_DIR/Pepper" 2>/dev/null || stat --printf='%s' "$FRAMEWORK_DIR/Pepper" 2>/dev/null)
DYLIB_SIZE_KB=$((DYLIB_SIZE / 1024))
success "Built Pepper.framework (${DYLIB_SIZE_KB}KB)"
success "  $FRAMEWORK_DIR/Pepper"
